on:
  workflow_dispatch:
    inputs:
      chosen-os:
        required: true
        type: choice
        options:
        - ubuntu-latest
        - macos-latest

jobs:
  test:
    runs-on: ["${{ inputs.chosen-os }}"]
    steps:
    - run: echo Hello world!
